-- SPDX-License-Identifier: MIT
import FrameEyeOsc.Layout
/-! Writes `abi/eye_server_layout.h` from `FrameEyeOsc.Layout`. With `--check`, fails
if the committed header differs, so the C side can never drift from the proved table. -/
open FrameEyeOsc.Layout

def hex (n : Nat) : String := "0x" ++ String.ofList (Nat.toDigits 16 n)

def macroName (pre : String) (f : Field) : String := pre ++ "_" ++ f.name.toUpper

def header : String := Id.run do
  let mut s := "/* Generated by `lake exe layout_header` from FrameEyeOsc/Layout.lean. Do not edit.\n" ++
    " * Layout.lean proves these fields tile their extents and fit the mapping. */\n" ++
    "#ifndef FRAMEEYEOSC_EYE_SERVER_LAYOUT_H\n#define FRAMEEYEOSC_EYE_SERVER_LAYOUT_H\n\n" ++
    s!"#define FE_SHM_SIZE {hex shmSize}\n#define FE_SHM_VERSION {shmVersion}\n" ++
    s!"#define FE_RECORD_OFF {hex recordOff}\n#define FE_RECORD_SIZE {hex recordSize}\n\n"
  for (pre, fs) in [("FE_OUTER", outer), ("FE_RECORD", record)] do
    for f in fs do
      s := s ++ s!"#define {macroName pre f}_OFF {hex f.off}\n#define {macroName pre f}_SIZE {hex f.size}\n"
    s := s ++ "\n"
  return s ++ "#endif\n"

def main (args : List String) : IO UInt32 := do
  let path := "abi/eye_server_layout.h"
  if args.contains "--check" then
    let cur ← IO.FS.readFile path
    if cur != header then
      IO.eprintln s!"{path} is stale; run `lake exe layout_header`"
      return 1
    IO.println s!"{path} matches FrameEyeOsc.Layout"
  else
    IO.FS.writeFile path header
    IO.println s!"wrote {path}"
  return 0
